<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container4cCCv1l\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container4cCCv1l/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container4cCCv1l.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container4cCCv1l\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container4cCCv1l\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '4cCCv1l',
    'container.build_id' => '107ebeae',
    'container.build_time' => 1609847999,
], __DIR__.\DIRECTORY_SEPARATOR.'Container4cCCv1l');
